### ISSUE TITLE
is-even? Are you serious?

### ISSUE THREAD

**Issue by backmeupplz** [cloudflare/service-worker-custom-build#1]
![Screen Shot 2021-03-08 at 4 33 17 PM](https://user-images.githubusercontent.com/3192028/110400178-0a9e6080-802c-11eb-938f-5d9327f8dc53.png)

# 😂😂😂

**Comment by xortive** [comment]
Heh, that was leftover from when we were using it to demonstrate importing a dependency. The actual functionality of said dependency didn't matter, so I picked a funny one :)
